CREATE TABLE users ( 
    id INT(11) NOT NULL AUTO_INCREMENT,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30),
    email VARCHAR(100) NOT NULL,
    pwd VARCHAR(255) NOT NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIME,

    
    PRIMARY KEY (id)
);